---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    12.0
    requiredRam:        2.0
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - storage
        - ram
        - root
