---
modules-search: [ local ]

instances:
- id:     cleanup
  module: shellprocess
  config: shellprocess_cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksopenswaphookcfg
  - luksbootkeyfile
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - packages
  - removeuser
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: custom
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
